# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-06-20 13:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fights', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fighter',
            name='birthday',
            field=models.CharField(max_length=255),
        ),
    ]
