# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-06-20 13:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fights', '0002_auto_20160620_1304'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fighter',
            name='location',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
