# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-06-15 01:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fights', '0002_fight_win'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fight',
            name='date',
            field=models.DateField(),
        ),
    ]
