# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-06-20 20:01
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fights', '0004_fight'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fight',
            name='loser',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='losers', to='fights.Fighter'),
        ),
        migrations.AlterField(
            model_name='fight',
            name='winner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='winners', to='fights.Fighter'),
        ),
    ]
