# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2017-01-20 12:24
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fights', '0007_event_sherdog_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='fight',
            name='event',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='fights.Event'),
        ),
    ]
