# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2017-01-23 11:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fights', '0008_fight_event'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='sherdog_url',
            field=models.CharField(blank=True, max_length=255, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='fighter',
            name='sherdog_url',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
