# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2017-01-24 13:12
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fights', '0009_auto_20170123_1126'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='fight',
            unique_together=set([('winner', 'loser', 'event')]),
        ),
    ]
