# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2017-02-09 18:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fights', '0012_event_dt_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='fighter',
            name='dt_birthday',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
