# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2017-02-10 09:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fights', '0013_fighter_dt_birthday'),
    ]

    operations = [
        migrations.AddField(
            model_name='fight',
            name='finish_type',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
