# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2017-02-10 17:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fights', '0014_fight_finish_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='fight',
            name='loser_experience',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='fight',
            name='winner_experience',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
