# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2017-02-21 17:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fights', '0015_auto_20170210_1724'),
    ]

    operations = [
        migrations.AddField(
            model_name='fight',
            name='loser_age',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='fight',
            name='winner_age',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
