# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2017-02-22 17:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fights', '0016_auto_20170221_1752'),
    ]

    operations = [
        migrations.AddField(
            model_name='fight',
            name='loser_streak',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='fight',
            name='winner_streak',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
