# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2017-05-09 08:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fights', '0018_fightquery'),
    ]

    operations = [
        migrations.AddField(
            model_name='fightquery',
            name='created_date',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
