# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2017-05-09 17:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fights', '0019_fightquery_created_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='fightquery',
            name='search_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='fightquery',
            name='updated_date',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
