# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2017-05-11 10:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fights', '0020_auto_20170509_1736'),
    ]

    operations = [
        migrations.AddField(
            model_name='fight',
            name='loser_int_age',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='fight',
            name='winner_int_age',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
